export const transactionData = [
  {
    id: 1,
    merchant: "Amazon",
    category: "Shopping",
    amount: 2400,
    status: "Completed",
    rewardCoins: 24,
    date: "2026-08-12",
  },
  {
    id: 2,
    merchant: "Swiggy",
    category: "Food",
    amount: 540,
    status: "Completed",
    rewardCoins: 5,
    date: "2026-08-11",
  },
  {
    id: 3,
    merchant: "Uber",
    category: "Travel",
    amount: 320,
    status: "Pending",
    rewardCoins: 3,
    date: "2026-08-10",
  },
  {
    id: 1,
    merchant: "flipkart",
    category: "Shopping",
    amount: 2400,
    status: "Completed",
    rewardCoins: 24,
    date: "2026-08-12",
  },
  {
    id: 2,
    merchant: "Swiggy",
    category: "Food",
    amount: 540,
    status: "Completed",
    rewardCoins: 5,
    date: "2026-08-11",
  },
  {
    id: 3,
    merchant: "vishruth",
    category: "Travel",
    amount: 320,
    status: "Pending",
    rewardCoins: 3,
    date: "2026-08-10",
  },
];
